# Generated by Django 3.1.2 on 2023-02-19 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("userId", models.AutoField(primary_key=True, serialize=False, verbose_name="userId")),
                ("username", models.CharField(default=None, max_length=200, verbose_name="username")),
                ("email", models.CharField(default=None, max_length=200, verbose_name="email")),
                ("createTime", models.DateTimeField(default=datetime.datetime.now)),
                ("blogAddress", models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name="blogAddress")),
                ("selfIntroduction", models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name="selfIntroduction")),
                ("userStatus", models.IntegerField(default=1, verbose_name="userStatus")),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
    ]
