# Generated by Django 3.2.18 on 2023-02-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(default=None, max_length=200, verbose_name='gender'),
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='user_info',
        ),
    ]
