# Generated by Django 3.2.18 on 2023-02-28 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20230228_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollows',
            fields=[
                ('followId', models.AutoField(primary_key=True, serialize=False, verbose_name='followId')),
                ('userFollowsId', models.CharField(default=None, max_length=200, verbose_name='userFollowsId')),
                ('userBeenFollowedId', models.CharField(default=None, max_length=200, verbose_name='userBeenFollowedId')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'user_follows',
            },
        ),
        migrations.CreateModel(
            name='UserLikes',
            fields=[
                ('likeId', models.AutoField(primary_key=True, serialize=False, verbose_name='likeId')),
                ('userLikesId', models.CharField(default=None, max_length=200, verbose_name='userLikesId')),
                ('userBeenLikedId', models.CharField(default=None, max_length=200, verbose_name='userBeenLikedId')),
                ('blogId', models.CharField(default=None, max_length=200, verbose_name='blogId')),
                ('userStatus', models.IntegerField(default=1, verbose_name='userStatus')),
                ('selfIntroduction', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='selfIntroduction')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'user_likes',
            },
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('loginId', models.AutoField(primary_key=True, serialize=False, verbose_name='loginId')),
                ('userId', models.CharField(default=None, max_length=200, verbose_name='userId')),
                ('token', models.CharField(default=None, max_length=200, verbose_name='token')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'user_login',
            },
        ),
        migrations.CreateModel(
            name='UserRoleList',
            fields=[
                ('listId', models.AutoField(primary_key=True, serialize=False, verbose_name='listId')),
                ('roleId', models.CharField(default=None, max_length=200, verbose_name='roleId')),
                ('userId', models.CharField(default=None, max_length=200, verbose_name='userId')),
                ('roles', models.CharField(default=None, max_length=200, verbose_name='token')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'user_role_list',
            },
        ),
    ]
