# Generated by Django 3.2.18 on 2023-02-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_userfollows_userlikes_userlogin_userrolelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False, verbose_name='listId')),
                ('roleName', models.CharField(default=None, max_length=200, verbose_name='roleId')),
                ('roleStatus', models.IntegerField(default=1, verbose_name='roleStatus')),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.DeleteModel(
            name='UserRoleList',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userRole',
            field=models.ManyToManyField(to='models.UserRole', verbose_name='userRole'),
        ),
    ]
