# Generated by Django 3.2.18 on 2023-02-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20230228_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='gender',
        ),
    ]
