# Generated by Django 3.2.18 on 2023-02-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_remove_userinfo_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='blogAddress',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='gender'),
        ),
    ]
