# Generated by Django 3.2.18 on 2023-02-28 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20230228_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='expireTime',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
    ]
