# Generated by Django 3.2.18 on 2023-03-01 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20230301_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetails',
            fields=[
                ('blogId', models.AutoField(primary_key=True, serialize=False, verbose_name='blogId')),
                ('userId', models.CharField(default=None, max_length=200, verbose_name='userId')),
                ('title', models.CharField(default=None, max_length=200, verbose_name='title')),
                ('imageUrls', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='imageUrls')),
                ('content', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='content')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now)),
                ('modifyTime', models.DateTimeField(default=datetime.datetime.now)),
                ('publishTime', models.DateTimeField(default=datetime.datetime.now)),
                ('modifyPersonId', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='modifyPersonId')),
                ('status', models.IntegerField(default=1, verbose_name='status')),
            ],
            options={
                'db_table': 'blog_details',
            },
        ),
    ]
