# Generated by Django 3.2.18 on 2023-03-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_alter_blogdetails_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikes',
            name='userBeenLikedId',
        ),
        migrations.AddField(
            model_name='userlikes',
            name='blogId',
            field=models.CharField(default=None, max_length=200, verbose_name='blogId'),
        ),
    ]
