# Generated by Django 3.2.18 on 2023-03-01 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0014_auto_20230301_1245"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetInfo",
            fields=[
                ("petId", models.AutoField(primary_key=True, serialize=False, verbose_name="petId")),
                ("petName", models.CharField(default=None, max_length=50, verbose_name="petName")),
                ("petGender", models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name="petGender")),
                ("petAge", models.IntegerField(blank=True, default=None, max_length=20, null=True, verbose_name="petAge")),
                ("petType", models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name="petType")),
                ("petBreed", models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name="petBreed")),
                ("petColor", models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name="petColor")),
                ("petTags", models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name="petTags")),
                ("petChipInfo", models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name="petChipInfo")),
                ("petVet", models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name="petVet")),
                ("petInsurance", models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name="petInsurance")),
                ("petVaccination", models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name="petVaccination")),
                ("createTime", models.DateTimeField(default=datetime.datetime.now)),
                ("modifyTime", models.DateTimeField(default=datetime.datetime.now)),
                ("modifyPersonId", models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name="modifyPersonId")),
                ("petStatus", models.IntegerField(default=1, verbose_name="petStatus")),
            ],
            options={
                "db_table": "pet_info",
            },
        ),
    ]
