# Generated by Django 3.2.18 on 2023-03-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_petinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='petinfo',
            table='pet_info',
        ),
    ]
