# Generated by Django 3.2.18 on 2023-03-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_alter_petinfo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='petinfo',
            name='userId',
            field=models.CharField(default=None, max_length=50, verbose_name='userId'),
        ),
    ]
