# Generated by Django 3.2.18 on 2023-03-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_petinfo_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinfo',
            name='petTags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
