# Generated by Django 3.2.18 on 2023-03-01 17:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_alter_petinfo_pettags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapCourseInfo',
            fields=[
                ('courseId', models.AutoField(primary_key=True, serialize=False, verbose_name='courseId')),
                ('courseTitle', models.CharField(default=None, max_length=200, verbose_name='courseTitle')),
                ('courseContent', models.CharField(default=None, max_length=200, verbose_name='courseContent')),
                ('courseImage', models.CharField(default=None, max_length=200, verbose_name='courseImage')),
                ('latitude', models.CharField(default=None, max_length=200, verbose_name='latitude')),
                ('longitude', models.CharField(default=None, max_length=200, verbose_name='longitude')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now)),
                ('courseStatus', models.IntegerField(default=1, verbose_name='courseStatus')),
            ],
            options={
                'db_table': 'map_course_info',
            },
        ),
        migrations.CreateModel(
            name='MapSchoolCourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.mapcourseinfo', verbose_name='courseId')),
            ],
            options={
                'db_table': 'map_school_course_info',
            },
        ),
        migrations.CreateModel(
            name='MapVetInfo',
            fields=[
                ('vetId', models.AutoField(primary_key=True, serialize=False, verbose_name='vetId')),
                ('vetName', models.CharField(default=None, max_length=200, verbose_name='vetName')),
                ('latitude', models.CharField(default=None, max_length=200, verbose_name='latitude')),
                ('longitude', models.CharField(default=None, max_length=200, verbose_name='longitude')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now)),
                ('vetStatus', models.IntegerField(default=1, verbose_name='vetStatus')),
            ],
            options={
                'db_table': 'map_vet_info',
            },
        ),
        migrations.CreateModel(
            name='MapSchoolInfo',
            fields=[
                ('schoolId', models.AutoField(primary_key=True, serialize=False, verbose_name='userId')),
                ('schoolName', models.CharField(default=None, max_length=200, verbose_name='schoolName')),
                ('latitude', models.CharField(default=None, max_length=200, verbose_name='latitude')),
                ('longitude', models.CharField(default=None, max_length=200, verbose_name='longitude')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now)),
                ('schoolStatus', models.IntegerField(default=1, verbose_name='schoolStatus')),
                ('course', models.ManyToManyField(through='models.MapSchoolCourseInfo', to='models.MapCourseInfo')),
            ],
            options={
                'db_table': 'map_school_info',
            },
        ),
        migrations.AddField(
            model_name='mapschoolcourseinfo',
            name='schoolId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.mapschoolinfo', verbose_name='schoolId'),
        ),
    ]
