# Generated by Django 3.2.18 on 2023-03-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_auto_20230301_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcourseinfo',
            name='courseContent',
            field=models.CharField(default=None, max_length=2000, verbose_name='courseContent'),
        ),
    ]
