# Generated by Django 3.2.18 on 2023-03-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_alter_mapcourseinfo_coursecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petinfo',
            name='petVet',
        ),
        migrations.AddField(
            model_name='petinfo',
            name='vetId',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='vetId'),
        ),
    ]
