# Generated by Django 3.2.18 on 2023-03-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_petinfo_petbirthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapvetinfo',
            name='createTime',
        ),
        migrations.AddField(
            model_name='mapvetinfo',
            name='address',
            field=models.CharField(default=None, max_length=200, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='mapvetinfo',
            name='companyInfo',
            field=models.CharField(default=None, max_length=200, verbose_name='companyInfo'),
        ),
        migrations.AlterField(
            model_name='mapvetinfo',
            name='latitude',
            field=models.FloatField(default=None, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='mapvetinfo',
            name='longitude',
            field=models.FloatField(default=None, verbose_name='longitude'),
        ),
    ]
