# Generated by Django 3.2.18 on 2023-03-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0023_auto_20230301_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapvetinfo',
            name='companyInfo',
        ),
        migrations.AddField(
            model_name='mapvetinfo',
            name='vetDescription',
            field=models.CharField(default=None, max_length=200, verbose_name='vetDescription'),
        ),
    ]
