# Generated by Django 3.2.18 on 2023-03-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0025_alter_mapvetinfo_vetdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlikes',
            name='userBeenLikedId',
            field=models.CharField(default=None, max_length=200, verbose_name='userBeenLikedId'),
        ),
    ]
