# Generated by Django 3.2.18 on 2023-03-08 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0027_alter_userinfo_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('imageId', models.AutoField(primary_key=True, serialize=False, verbose_name='imageId')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now)),
                ('modifyTime', models.DateTimeField(default=datetime.datetime.now)),
                ('modifyPersonId', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='modifyPersonId')),
                ('category', models.IntegerField(default=1, verbose_name='category')),
                ('status', models.IntegerField(default=1, verbose_name='status')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.AddField(
            model_name='blogdetails',
            name='imageIDs',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
    ]
