# Generated by Django 3.2.18 on 2023-03-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0028_auto_20230308_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('blogId', models.AutoField(primary_key=True, serialize=False, verbose_name='blogId')),
                ('imageUrls', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='imageUrls')),
            ],
            options={
                'db_table': 'blog_images',
            },
        ),
        migrations.RemoveField(
            model_name='blogdetails',
            name='imageIDs',
        ),
        migrations.RemoveField(
            model_name='blogdetails',
            name='imageUrls',
        ),
    ]
