# Generated by Django 3.2.18 on 2023-03-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0029_auto_20230315_1055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogImages',
        ),
    ]
