# Generated by Django 3.2.18 on 2023-03-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0031_blogimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetails',
            name='tag',
            field=models.CharField(default=None, max_length=100, verbose_name='title'),
        ),
    ]
