"""
Django settings for petopia project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os  # import os to support dir
from pathlib import Path
from datetime import timedelta  # for background tasks

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "(+3tb1)gwqon63mmtgxvicsc-*)s8^cx8%kib0@w6^kdl2d@#u"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["petopia.top", "bk.petopia.top", "localhost"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "api",  # import api
    "models",  # import models
    "sslserver",  # import sslserver to enable ssl
    # "background_task",  # import background_task
]
# INSTALLED_APPS += ["background_task"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # to enable cors
    'django.middleware.csrf.CsrfViewMiddleware', # should be ahead of common middleware
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "petopia.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "petopia.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# Here we use mysql instead of default database sqlite3
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "petopia",  # database name
        "HOST": "192.168.1.33",
        "PORT": "11001",
        "USER": "root",
        "PASSWORD": "Petopia123@",
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/images/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, '/images/')]

# here we set default fields using django BigAutoField
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"  # This is only available in django 3.2 and is used to set automatic growth fields

# Cors settings
CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

CORS_ALLOW_HEADERS = (
    "XMLHttpRequest",
    "X_FILENAME",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "Pragma",
    "x-token",
)

# REST_FRAMEWORK = {
#     "DEFAULT_AUTHENTICATION_CLASSES":['rest_framework_jwt.authentication.JSONWebTokenAuthentication',],
# #     # "DEFAULT_PERMISSION_CLASSES":['api.utils.permission.myPermission'], # There will be an error if we release the global.
# #     # "UNAUTHENTICATED_USER": lambda :"Anonymous User" # Anonymous User Method 1
# #     # "UNAUTHENTICATED_USER":None, # Anonymous user Method 2, recommended
# "DEFAULT_VERSIONING_CLASS":"rest_framework.versioning.URLPathVersioning", # The default global configuration is displayed in a, p, i view.py
# #     # 'DEFAULT_VERSION': 'v1',
# #     # 'ALLOWED_VERSIONS': ['v1', 'v2'],
# #     # 'VERSION_PARAM': 'version', # The version parameter name is version by default
# #     # 'DEFAULT_PARSER_CLASSES': ['rest_framework.parsers.JSONParser','rest_framework.parsers.FormParser'], # serializer
# #     # "PAGE_SIZE": 2,
# }

# Background task settings
# MAX_RUN_TIME = timedelta(minutes=15)
# BACKGROUND_TASK_RUN_ASYNC = True
# BACKGROUND_TASK_ASYNC_THREADS = 4

MEDIA_ROOT = os.path.join(BASE_DIR, 'static/images')
MEDIA_URL = '/static/images/'
